name: Deploy ClimateScope App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run basic tests
      run: |
        python -c "import streamlit; print('Streamlit import successful')"
        python -c "import pandas; print('Pandas import successful')"
        python -c "import sklearn; print('Scikit-learn import successful')"
        python -c "import plotly; print('Plotly import successful')"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Streamlit Cloud
      run: |
        echo "Application ready for deployment"
        echo "Visit: https://share.streamlit.io to deploy this repository"